name: Continuous Deployment

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: self-hosted

        steps:
            - uses: actions/checkout@v2
            - name: Stop older Docker service
              run: docker rm -f majestic

            - name: Build new Docker image
              run: docker build -t mirac/majestic .

            - name: Run the new Docker container
              run: docker run -d -p 8035:3000 --name majestic -e "DIRECTUS_BEARER=${{ secrets.DIRECTUS_BEARER }}" --restart unless-stopped mirac/majestic
