name: Continuous Deployment

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: self-hosted

        steps:
            - uses: actions/checkout@v2
            - name: Install Dependencies and Build Majestic
              run: |
                  yarn
                  yarn build

            - name: Reload the PM2 Ecosystem
              run: |
                  pm2 reload ecosystem.config.js
                  pm2 save
